### ISSUE TITLE
Unable to use with Typescript

### ISSUE THREAD

**Issue by samitha9125** [PiotrKujawa/redux-deep-persist#6] opened 2023-03-15 16:23 UTC
## Steps to reproduce

Add the following lines to your typescript file.

```
const config = getPersistConfig({
    key: 'root',
    storage, // whatever storage you use
    whitelist: ['property1.a1.b1', 'property1.a2.b2.c2', 'property2.a2'],
    rootReducer // your root reducer must be also passed here
});
```

## Expected Outcome
ESLint does not show any errors.

## Actual Outcome
ESLint repeatedly say `Unsafe call of an 'any' typed value` and `Unsafe assignment of an any type value`

**Comment by PiotrKujawa** [comment] 2023-03-15 17:20
Hi @samitha9125, can you please provide more details? I checked this and the typescript validates everything as expected.
Where do you get this error from? Is this coming from getPersistConfig call? Can you show me your entire config and reducers? Also, any screenshot of the error would be helpful to me. Thank you.

**Comment by PiotrKujawa** [comment] 2023-03-22 11:42
Closing. I couldn't reproduce this issue. Without more details, I won't be able to help.

**Closed as completed by PiotrKujawa** 2023-03-22 11:42 UTC
